Dont publish migration if migration exists
owen-it/laravel-auditing pull request #692
Opened 2022-02-22 13:03 UTC by MortenDHansen

2022-02-22 13:34 UTC, anteriovieira requested changes

2022-02-22 13:34 UTC, anteriovieira commented on src/AuditingServiceProvider.php
> +            if (!class_exists('CreateAuditsTable')) {
check if the file exists instead of the class.

2022-02-22 13:36 UTC, MortenDHansen commented
> 

Yeah, but i don't think you actually need to use the anonymous migrations if you don't want to. If we expect all existing migrations to be created as a class and we dont change how we publish it, then the class check should be enough. Spatie seems use same approach: https://github.com/spatie/laravel-translation-loader/blob/main/src/TranslationServiceProvider.php

2022-02-22 13:38 UTC, anteriovieira commented
Looks good to me! thanks

2022-02-22 13:39 UTC, merged

2022-04-26 09:13 UTC, sarukomine commented
@MortenDHansen the change is not working for me, at least not working for Laravel Framework 9.9.0, I still can keep on publishing migration files. Maybe we should change the way to check if file exists instead of the class.

2022-04-26 09:31 UTC, MortenDHansen commented
Yeah, maybe my brilliant simple fix was not as brilliant as i figured, and a bit too simple :/