Support for auditSync and auditDetach on Auditable custom Pivot class
owen-it/laravel-auditing pull request #954
Opened 2024-07-03 10:58 UTC by txdFrancesco

Allow the use of auditSync and auditDetach on BelongsToMany relations where the pivot class is an Auditable class.

This is useful in cases where the relation model is itself a Laravel model and may be updated (and thus audited) indipendently  from the related models, without requring dedicated code around every ->auditSync call on the related models.

2024-07-03 13:43 UTC, willpower232 requested changes
are you able to correct your spaces to match the rest of the code and add some tests for the functionality you've added?

2024-07-03 13:52 UTC, txdFrancesco commented
For the spaces sure, for the tests I'll need to add a couple of models to reproduce. 
Users -> GroupMembers (with 'role' column) -> Groups could be an example of my case. Let me know if you have a better/preferred example structure. I'll update when I'm done, thanks

2024-07-03 16:51 UTC, txdFrancesco commented
I added some tests that cover sync, attach and detach with an Auditable custom Pivot class.
AuditAttach is not affected by my code change, I put in the test anyway for completeness. Let me know if it is better to remove it.

The other tests are failing without the code change and are passing now.

2024-09-13 07:27 UTC, willpower232 requested changes
some final spaces and maybe wake up github actions

2024-09-13 07:27 UTC, willpower232 commented on src/Auditable.php
> +        if($pivotClass !== Pivot::class && is_a($pivotClass, ContractsAuditable::class, true)) {
```suggestion
        if ($pivotClass !== Pivot::class && is_a($pivotClass, ContractsAuditable::class, true)) {
```

2024-09-13 07:27 UTC, willpower232 commented on src/Auditable.php
>          $old = $relationCall->get($columns);
```suggestion

        $old = $relationCall->get($columns);
```

2024-09-13 07:27 UTC, willpower232 commented on src/Auditable.php
> +        if($pivotClass !== Pivot::class && is_a($pivotClass, ContractsAuditable::class, true)) {
```suggestion
        if ($pivotClass !== Pivot::class && is_a($pivotClass, ContractsAuditable::class, true)) {
```

2024-10-24 07:17 UTC, bmoex commented
I think `auditAttach` should be checked too if you want to implement fully

2024-10-24 08:51 UTC, txdFrancesco commented
> some final spaces and maybe wake up github actions

Sorry for the inconvenience, I'm not sure what should I do to make this pull request go through.
The spacing was fixed by your commit (I just fixed one more line), but it's not clear to me what you mean with "wake up github actions". Could you explain or point me in the right direction please?
Thank you

2024-10-24 08:57 UTC, txdFrancesco commented
> I think `auditAttach` should be checked too if you want to implement fully

The bug was caused by the way the detach method creates the query to delete the pivot class (creating a new instance and not retrieving the one in the database). Attaching is not affected by it (there is no instance to retrieve), applying the changes would just remove the "created" audit on the pivot class, which is against the idea of having an auditable pivot class.

A full solution would be to rework how the detach method builds the query instead of wrapping with withoutAuditing, but frankly I don't know the codebase enough to make such an impactful change for what is an edge usecase.

2025-01-30 22:59 UTC, onlime commented
> The bug was caused by the way the detach method creates the query to delete the pivot class (creating a new instance and not retrieving the one in the database). Attaching is not affected by it (there is no instance to retrieve), applying the changes would just remove the "created" audit on the pivot class, which is against the idea of having an auditable pivot class.

Thanks a lot @txdFrancesco for this explanation. Would be super nice if this could be supported in the future.

@MortenDHansen is there something in the works for V14? https://github.com/owen-it/laravel-auditing/pull/984/commits/f49ab23ede14fd5c3282264b4a177a22fbb36ae0 looks promising, or at least it's a smart refactor to move that logic into a separate `AuditsPivotRecords` trait.
Thanks a lot for this great package and very cool to see some progress here.

2025-02-15 16:35 UTC, willpower232 approved these changes
seems fine to me, not sure when is good to merge this @erikn69 perhaps just needs a pint/phpstan run after merging your other PR?

2025-02-26 11:18 UTC, willpower232 requested changes
@txdFrancesco are you able to update the PR now that the factories are modernised?

2025-02-26 14:06 UTC, txdFrancesco reviewed
Should be done, test are passing on my machine. @willpower232 can you approve the action workflow? [here](https://github.com/owen-it/laravel-auditing/actions/runs/13545615910) it says it needs approval from a mantainer

2025-02-26 14:13 UTC, willpower232 approved these changes
looking good to me, thanks for the quick response

@erikn69 time for merging and v14?

2025-02-26 14:26 UTC, erikn69 commented
@willpower232 the tests were not run on this change, I won't have time to review this for at least a couple of weeks, if you reviewed it and it won't cause problems feel free to merge it and make the release for v14, you would also have to put the note for the event breaking change (I couldn't find why it works differently in certain scenarios)

2025-02-26 16:40 UTC, merged